### ISSUE TITLE
Create a base template for ROS2 RADI

### ISSUE THREAD

**Issue by trunc8** [TheRoboticsClub/gsoc2021-Siddharth_Saha#5]

**Comment by jmplaza** [comment]
This issue is related to https://github.com/JdeRobot/RoboticsAcademy/issues/796

**Comment by trunc8** [comment]
Hi, this is a [demo](https://youtu.be/61k0kLDCaqg) of the current status of the ROS2 RADI.

I'm making a design decision and would like your feedback.
Foxy RADI leverages the noetic branch of RoboticsAcademy. I will commit my modifications on [my fork](https://github.com/trunc8/RoboticsAcademy) of the RoboticsAcademy repo, instead of here on collab.
This will enable future developers to trace back the history of unchanged files.

I have already made a branch titled issue 796 in my fork, and would be pushing changes after some more clean-up.

**Comment by jmplaza** [comment]
Nice demo @trunc8 !!

Feel free to create the "foxy branch" in RoboticsAcademy repo, just develop there the corresponding Dockerfile, copy all the resources you need, and create a directory for the Amazon Warehouse exercise. That branch will be in alpha state for a while.

**Comment by trunc8** [comment]
Solved and tested below after merging the PR and building from the parent branch.

![image](https://user-images.githubusercontent.com/50488330/124136900-d18a7000-daa2-11eb-8373-e2d5c132879a.png)
